[package]
name = "install_gtk"
version = "0.1.2"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["stream", "json"] }
tokio = { version = "1.45.1", features = ["full"] }
serde_json = "1.0.140"
